def genass_sorry(s1, s2, s3, s4, s5, s6, s7, s8, s9, name1, name2, name3):
    rtn = '''[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 640
PlayResY: 360

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: /Users/rainy/video.mp4
Video AR Mode: 4
Video AR Value: 1.777778
Video Zoom Percent: 1.250000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: arial,Arial Unicode MS,45,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: name,Arial Unicode MS,60,&H000000FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.20,0:00:02.40,arial,,0,0,0,,''' + s1 + '''
Dialogue: 0,0:00:02.80,0:00:04.90,arial,,0,0,0,,''' + s2 + '''
Dialogue: 0,0:00:05.30,0:00:07.50,arial,,0,0,0,,''' + s3 + '''
Dialogue: 0,0:00:07.60,0:00:09.70,arial,,0,0,0,,''' + s4 + '''
Dialogue: 0,0:00:10.00,0:00:11.50,arial,,0,0,0,,''' + s5 + '''
Dialogue: 0,0:00:11.60,0:00:13.20,arial,,0,0,0,,''' + s6 + '''
Dialogue: 0,0:00:13.30,0:00:17.00,arial,,0,0,0,,''' + s7 + '''
Dialogue: 0,0:00:17.90,0:00:19.70,arial,,0,0,0,,''' + s8 + '''
Dialogue: 0,0:00:19.80,0:00:20.50,arial,,0,0,0,,''' + s9 + '''
Dialogue: 0,0:00:00.00,0:00:11.46,name,,0,0,0,,{\pos(225,71)}''' + name2 + '''
Dialogue: 0,0:00:17.61,0:00:21.00,name,,0,0,0,,{\pos(225,71)}''' + name2 + '''
Dialogue: 0,0:00:12.96,0:00:16.16,name,,0,0,0,,{\pos(225,71)}''' + name2 + '''
Dialogue: 0,0:00:17.61,0:00:21.00,name,,0,0,0,,{\pos(430,61)}''' + name1 + '''
Dialogue: 0,0:00:00.00,0:00:11.46,name,,0,0,0,,{\pos(430,61)}''' + name1 + '''
Dialogue: 0,0:00:12.96,0:00:16.16,name,,0,0,0,,{\pos(430,61)}''' + name1 + '''
Dialogue: 0,0:00:11.46,0:00:12.96,name,,0,0,0,,{\pos(312,56)}''' + name3 + '''
Dialogue: 0,0:00:16.16,0:00:17.61,name,,0,0,0,,{\pos(312,56)}''' + name3

    return rtn



def genass_chinese(s1, s2):
    rtn = '''[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 300
PlayResY: 300

[Aegisub Project Garbage]
Video File: /Users/rainy/Documents/Adobe/Premiere Pro/12.0/chinese_3.mp4
Video AR Mode: 4
Video AR Value: 1.000000
Video Zoom Percent: 1.250000
Video Position: 107

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: 中文,Arial,28,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: arial,Arial Unicode MS,45,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: name,Arial Unicode MS,45,&H000000FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:01.45,arial,,0,0,0,,''' + s1 + '''
Dialogue: 0,0:00:01.46,0:00:04.26,arial,,0,0,0,,''' + s2

    return rtn


def genass_wangjingze(s1, s2, s3, s4):
    rtn = '''[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 974
PlayResY: 602

[Aegisub Project Garbage]
Audio File: /Users/rainy/Downloads/template_origin.mp4
Video File: /Users/rainy/Downloads/template_origin.mp4
Video AR Mode: 4
Video AR Value: 1.617940
Video Zoom Percent: 0.875000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: 中文,Arial,28,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: arial,Arial Unicode MS,70,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: name,Arial Unicode MS,45,&H000000FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:01.30,arial,,0,0,0,,''' + s1 + '''
Dialogue: 0,0:00:01.30,0:00:03.10,arial,,0,0,0,,''' + s2 + '''
Dialogue: 0,0:00:03.10,0:00:04.40,arial,,0,0,0,,''' + s3 + '''
Dialogue: 0,0:00:04.40,0:00:06.40,arial,,0,0,0,,''' + s4

    return rtn


def genass_roll(s1, s2, s3):
    rtn = '''[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1280
PlayResY: 720

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: /Users/rainy/Downloads/roll.mp4
Video AR Mode: 4
Video AR Value: 1.777778
Video Zoom Percent: 0.625000
Active Line: 2
Video Position: 270

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: 中文,Arial,28,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: arial,Arial Unicode MS,90,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: name,Arial Unicode MS,45,&H000000FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: ou,Arial Unicode MS,140,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:03.50,arial,,0,0,0,,''' + s1 + '''
Dialogue: 0,0:00:03.50,0:00:09.00,arial,,0,0,0,,''' + s2 + '''
Dialogue: 0,0:00:07.50,0:00:11.00,ou,,0,0,0,,{\pos(492,364)}''' + s3

    return rtn
